### ISSUE TITLE
Links are not working

### ISSUE THREAD

**Issue by ghelapratik** [OnsenUI/awesome-onsenui#1]
The links at tutorials.onseui.com are not working. Can you please check them ??

**Comment by asialgearoid** [comment]
Which links? We don't have a `tutorials.onsen.io` domain anymore. Maybe you want the [Playground](https://onsen.io/playground/).

In any case, I will close this issue as this is not the website repository. If there are still broken links, please file a new issue at https://github.com/OnsenUI/onsen.io.
